---
title: "Mi Vida"
date: 2020-05-31
---
theme: minima
title: Neha Rani
author: nrani24
email: nehacutiy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Summary of Neha Rani's life

# social links
instagram_username: neha__rani # DO NOT include the @ character, or else the build will fail!
github_username:  nrani24 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
